### ISSUE TITLE
"No artifacts were found" error

### ISSUE THREAD

**Issue by nazar-pc** [tauri-apps/tauri-action#240]
We just noticed that tauri-apps/tauri-action@v0 action started failing on Windows with this:
```
Expected artifacts paths:
D:\a\subspace-desktop\subspace-desktop\src-tauri\target\release\bundle\msi\Subspace Desktop_0.1.0_x64_en-US.msi
D:\a\subspace-desktop\subspace-desktop\src-tauri\target\release\bundle\msi\Subspace Desktop_0.1.0_x64_en-US.msi.zip
D:\a\subspace-desktop\subspace-desktop\src-tauri\target\release\bundle\msi\Subspace Desktop_0.1.0_x64_en-US.msi.zip.sig
Error: No artifacts were found.
```

I suspect that this might be caused by whitespace in the path, going to verify that next. Action worked fine just 2 days ago.

https://github.com/subspace/subspace-desktop/runs/5458405324?check_suite_focus=true

**Comment by FabianLars** [comment]
Because your project still uses tauri's beta version you need to pin the action to `tauri-action@v0.2`

**Comment by bicarlsen** [comment]
As a note, the examples on the [Code Signing macOS Applications guide](https://tauri.app/v1/guides/distribution/sign-macos) and in the [README of this repo](https://github.com/tauri-apps/tauri-action) still use version 0

**Comment by bicarlsen** [comment]
Also see Issue #368.

**Comment by FabianLars** [comment]
> As a note, the examples on the [Code Signing macOS Applications guide](https://tauri.app/v1/guides/distribution/sign-macos) and in the [README of this repo](https://github.com/tauri-apps/tauri-action) still use version 0

What else should the examples show? Sure, we could force 0.3 but 0.4 is relatively close with important fixes so i'd prefer if all users automatically get that instead of having to change their workflow files (especially since users would have to notice that there is an update first). And recommending `@dev` is not stable enough.

> Also see Issue https://github.com/tauri-apps/tauri-action/issues/368.

to be fair, that one is kinda unrelated, just the same generic error message.

**Comment by bicarlsen** [comment]
I think making a note somewhere about the versioning could help because it appears this issue has come up several times. I'm not super familiar with GitHub actions yet so it could just be a lack of my knowledge about how to search for which version or branch of the action to use.

**Comment by FabianLars** [comment]
i don't think there is much to document on the versioning yet.
Use 0.2 if you're using tauri=1.0.0-beta.8 (which we don't support anymore therefore won't mention it)
Use `v0` for everything, or lock it to `v0.3` to be safe(r) from potential breaking changes
Don't use `@dev` directly unless you really have to (preferably locking it to a commit rev) - this won't be documented either because the dev branch is not stable for most.

Buuut feedback was noted and we'll look into it once we have a clearer picture of all things concerning the action, thank you!
