### ISSUE TITLE
tauri-action README contains `yarn build` instead of `yarn tauri:build`

### ISSUE THREAD

**Issue by georgik** [tauri-apps/tauri-action#245]
tauri-action README contains build action with commands: `yarn && yarn build`

These commands build just JS part, but Rust part is missing so the job fails: https://github.com/georgik/idf-installer-tauri/runs/5675921396?check_suite_focus=true#step:9:17

`Error: No artifacts were found.`

The build works without problem after changing the command to: `yarn && yarn tauri:build`
https://github.com/georgik/idf-installer-tauri/blob/main/.github/workflows/build-installer.yaml#L55

**Comment by FabianLars** [comment]
That's not really the problem here. tauri-action is supposed to build the tauri app (so if you have configured the beforeBuildCommand to build your app you probably don't need to build the frontend in the step before that).

The default command it runs is `yarn tauri build` which is incompatible with the vue-cli template, so you'd need to specify a `tauriScript` property with `yarn tauri:build` instead. Of course it's fine if your variant works too, but the one i tried to explain is the "canon" way.

**Comment by georgik** [comment]
Thank you for explanation @FabianLars .

I was following steps for creating new app using `yarn` with Vue. The app worked fine, then I've added GitHub Action described in README from this repo and build failed on artifacts not found. It might be useful to consider adding there a check to GitHub action for uploading artifacts or add message with explanation, because it's not obvious from error message what's wrong.

Again, thank you very much for advice. Tauri is really awesome.
