### ISSUE TITLE
Workflow takes a lot of time to build (on windows, github)

### ISSUE THREAD

**Issue by ahqsoftwares** [tauri-apps/tauri-action#294]
This problem occurs when the apps build in github.
It has to download and compile every single dependency before it compiles the app, which takes almost 20minutes.

Is there any way to pre compile the main tauri deps with the action to speed up build time?

**Comment by ahqsoftwares** [comment]
![Screenshot_20220811-084540_Firefox](https://user-images.githubusercontent.com/84524025/184059249-be12d4e6-bc6c-4021-8d2d-5b9ef537ca31.png)

Took a total of almost 20minutes

**Comment by FabianLars** [comment]
You could add a cache, but it's only helpful if you release your app multiple times a week, because github caches get removed after 1 week.

Build times over 10 minutes are normal for _release_ builds, but what's weird here is 6mins plus 12mins, something doesn't seem right about this, unless it takes 5 minutes to install your dependencies.
What i think happens is that you build, at least your frontend, twice (second time via beforeBuildCommand?). Just keep in mind that tauri-action invokes `tauri build` for you.
