### ISSUE TITLE
.dmg generated by tauri action cannot be mounted

### ISSUE THREAD

**Issue by MaKleSoft** [tauri-apps/tauri-action#30]
<img width="372" alt="Screenshot 2020-07-25 at 17 51 42" src="https://user-images.githubusercontent.com/1270940/88460854-a6b19800-ce9f-11ea-8210-92d5b4d37932.png">

Workflow file: https://github.com/padloc/padloc/blob/tauri-v3.1.1/.github/workflows/build-tauri-2.yml
Artifacts: https://github.com/padloc/padloc/releases/tag/tauri-v3.1.1

**Comment by nothingismagick** [comment]
can confirm. thanks for reporting

**Comment by zicklag** [comment]
I do not have a Mac myself to test it on, but I have a user of my application who has reported a similar [failure](https://discourse.charmhub.io/t/juju-lens-v0-1-0-new-desktop-application-with-ssh-support/3613/23?u=zicklag) for the App.tgz: "You can't open "juju-lens_0.1.0_x64" because it may be damaged or incomplete. He said that the DMG will not work either.

Artifacts: https://github.com/katharostech/juju-lens/releases/tag/v0.1.1

**Comment by lucasfernog** [comment]
A possible reason is the lack of code signing, see https://github.com/create-dmg/create-dmg/issues/52

**Comment by chriamue** [comment]
You can read here how to start unsigned DMGs: https://github.com/create-dmg/create-dmg/issues/52#issuecomment-377878026

**Comment by FabianLars** [comment]
Closing this because we can't do anything if it's about code signing.
