### ISSUE TITLE
Simplify action

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri-action#354]
A couple months ago I rewrote this action as https://github.com/JonasKruckenberg/tauri-build and after reading some issues here, namely #342, #320, #215, #298, #192 and #215 the root issue is that our action just tries to do too much and even the fixes I implemented in my personal action wouldn't do much to alleviate this.
I propose to do this instead:
- [`tauri-build`](https://github.com/JonasKruckenberg/tauri-build) as a basis
- ~~implement the automatic Tauri initialisation~~
- provide a couple examples of the action integrating with `softprops/action-gh-release@master` and others to replicate the functionality of the current version. The readme of my action can use as the base of this too.
- release this code in a major bump

**Comment by JonasKruckenberg** [comment]
> - implement the automatic Tauri initialisation

<img width="1119" alt="Screenshot 2023-01-09 at 17 16 56" src="https://user-images.githubusercontent.com/25329995/211355452-52c2359c-572a-461c-b2ae-52054f386ac1.png">

Feedback on discord, and I do agree with this. Maybe we can have another example that showcases this feature instead.

**Comment by FabianLars** [comment]
i'm a bit torn about this tbh. Like i said many times i myself don't use the action and prefer manual build steps instead. The problem is just that many many users have no idea about gh action or ci in general and really only use it because there is no cross platform support. so a one-liner really is super good for them, if that one-liner works of course...
-> We basically have 2 target audiences here.

Then there are some features often asked for like the latest.json generation which you can't really do outside of the action itself in a nice and noob-friendly way.

The Tauri init stuff is a bit weird, but i heard often enough that core wants to keep it that i stopped caring about it - and i actually did see it used in the wild a few times.

Maybe we should start with a refactor first and see if we can clean up the code base a bit before making such drastic changes, including cutting features? I started doing that a few days ago here <https://github.com/tauri-apps/tauri-action/tree/refactor> but didn't end up opening a PR for discussion -> this branch only turns the repo into a single package which was my main pain point working on issues here.

**Comment by JonasKruckenberg** [comment]
Hmm I mean yeah I do see that people might get it wrong, but still. The benefits far outweigh the problems here in my opinion.
I opened a draft PR with the contents of tauri-build now btw, so y'all can have a look at how I would envision things to look. (It's a pretty big change now as I kept almost none of the current code and files bc the Tauri-build setup works, a mix of both repos would likely not on the first try)

**Comment by amrbashir** [comment]
> Then there are some features often asked for like the latest.json generation which you can't really do outside of the action itself in a nice and noob-friendly way.

That I think we should keep, other features could be outsourced to other github actions and we provide examples on how to integrate them.

**Comment by JonasKruckenberg** [comment]
> That I think we should keep

I honestly think we should consider making this part of the CLI even

**Comment by amrbashir** [comment]
but the cli doesn't manage any versioning or releases, so I think it should stay on tauri-action side

**Comment by JonasKruckenberg** [comment]
> but the cli doesn't manage any versioning or releases, so I think it should stay on tauri-action side

Okay so I think I actually don't know what that latest.json thingy does hahaha
