### ISSUE TITLE
Tauri GitHub action failed because of Github's deprecated feature

### ISSUE THREAD

**Issue by meel-hd** [tauri-apps/tauri-action#358]
# Usage
I am using the Tauri Github action to build and release an app, the problem is lately the action started failing.
I am using the same action in the  [README.md](https://github.com/tauri-apps/tauri-action#uploading-the-artifacts-to-a-release) of Tauri Github Action.

# Warnings
**Before** the actions started **failing** it prompted some warnings as in the picture
![image](https://user-images.githubusercontent.com/92476321/213537617-cb56a14a-0d8f-4284-ad49-a47d25f0ff81.png)
_The waring_ is related to some **deprecated Github actions commands**, [see here.](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

# Current Failure
According to Github they are not supporting the commands **save-state** and **set-output** anymore, which unfortunately are used by tauri-action and causes its failure.
this is a picture of its behaviour
![image](https://user-images.githubusercontent.com/92476321/213539760-0e98f97c-29b0-41ca-bdbd-d0fbb513ae67.png)

**Comment by FabianLars** [comment]
save-state and set-output still work until end of May. The error is unrelated and _should_ be fixable by manually specifying the permissions as shown here: https://github.com/tauri-apps/tauri-action/pull/286/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R57

Since this issue is getting more popular for whatever reason i'll add it to the readme example.
