### ISSUE TITLE
Allow option for only generating debug builds

### ISSUE THREAD

**Issue by Raphiiko** [tauri-apps/tauri-action#364]
I'm looking for a way to only generate debug builds.

Currently it seems that when I set `includeDebug: true`, it builds and uploads the release versions, followed by building and uploading the debug versions. 

To only generate debug builds, I tried setting `args: --debug` instead, however it will only try to upload release artifacts, which fails as only debug artifacts are present. 

I apparently need to set `includeDebug: true` for it to consider uploading debug artifacts, but when I combine the two options, it just tries building a second time, this time by setting the debug flag twice (`--debug --debug`), which again fails the action.

Is there some way to accomplish what I'm looking for, or is there a possibility this could be added? (e.g. a `includeRelease` flag, to mirror the existing `includeDebug`)

**Comment by FabianLars** [comment]
> Is there some way to accomplish what I'm looking for

By adding it to the plugin itself. Or by not using the plugin and uploading the files yourself.

> or is there a possibility this could be added?

yep, that was the plan after https://github.com/tauri-apps/tauri-action/pull/362

**Comment by Raphiiko** [comment]
> By adding it to the plugin itself. 

Alright, for now I've forked the action and added an option for this. 
In case this functionality could be merged back, I've submitted a PR for them here: #365.

**Comment by spectraldoy** [comment]
When I try to set `includeRelease: false` in the workflow file, I get this warning:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/41366802/235291681-8510d299-420d-4f53-b3fe-254ca17b5d8f.png">

And the workflow compiles both a release and debug version (I have `includeDebug: true`). Am I doing something wrong? I'm using `tauri-apps/tauri-action@v0` in my workflow file, but am not able to compile only a debug version.

I also wanted to ask: if I use `args: '--debug'` instead of `includeDebug: true`, will this have the desired effect of compiling only a debug version, and not a release version?

Thank you.

**Comment by FabianLars** [comment]
> Am I doing something wrong?

IncludeRelease will be part of v0.4 which is not released yet, meaning you can only use it if you consume the action from git (`tauri-apps/tauri-action@dev` or via a commit hash)

> I also wanted to ask: if I use args: '--debug' instead of includeDebug: true, will this have the desired effect of compiling only a debug version, and not a release version?

It should compile only a debug version, but it won't be able to upload it yet.
