### ISSUE TITLE
Can't make builds using v0.4

### ISSUE THREAD

**Issue by dxlbnl** [tauri-apps/tauri-action#459]
I've just setup a project, but the builds fail when I use the action@0.4 https://github.com/wolbodo/bifrost/actions/runs/4925815628
When switching back to @0.3 they seem to pass. https://github.com/wolbodo/bifrost/actions/runs/4926895235
The builds fail for different reasons, but all in the tauri-action

- mac and windows seem to not be able to find standard stuff like crate::* and derive
- Linux seems to be building, but it outputs the bins in a different location than tauri-action expects.

**Comment by FabianLars** [comment]
The issue was the .cargo/config.toml file you removed in your last pr: https://github.com/wolbodo/bifrost/commit/93af0e89171cd652a6d2dbe84d363f441a373c9a#diff-9f4339997afd37f5dcd70929ffdb5ffc759f80f39d873b0b7a943080dab088b4

In this context the action doesn't do much more than running `tauri build` the same as you'd do locally, so the config.toml file forced it to build for Linux, which also changed the target dir which is why the Linux runner also failed.

Also, this wasn't specific to v0.4, it was just a coincidence that you removed the config in the same commit you switched to v0.3 😅
