### ISSUE TITLE
Error: No artifacts were found. (need to provided a package.json with name, version fields).

### ISSUE THREAD

**Issue by liudonghua123** [tauri-apps/tauri-action#561]
Hi, I got `Error: No artifacts were found` when I use this github action. It seems the default package name `app` is not the same as `productName`, it conflicts actually. 

https://github.com/tauri-apps/tauri-action/blob/e981d397cbf7b31f45d4e192d817430336c7647a/src/utils.ts#L210-L212

The final logs:

```
......
   Compiling state v0.5.3
    Finished release [optimized] target(s) in 5m 08s
    Bundling desmos-app_0.1.1_amd64.deb (/home/runner/work/www.desmos.com/www.desmos.com/src-tauri/target/release/bundle/deb/desmos-app_0.1.1_amd64.deb)
    Bundling desmos-app_0.1.1_amd64.AppImage (/home/runner/work/www.desmos.com/www.desmos.com/src-tauri/target/release/bundle/appimage/desmos-app_0.1.1_amd64.AppImage)
    Finished 2 bundles at:
        /home/runner/work/www.desmos.com/www.desmos.com/src-tauri/target/release/bundle/deb/desmos-app_0.1.1_amd64.deb
        /home/runner/work/www.desmos.com/www.desmos.com/src-tauri/target/release/bundle/appimage/desmos-app_0.1.1_amd64.AppImage

Looking for artifacts in:
/home/runner/work/www.desmos.com/www.desmos.com/src-tauri/target/release/bundle/deb/app_0.1.0_amd64.deb
/home/runner/work/www.desmos.com/www.desmos.com/src-tauri/target/release/bundle/appimage/app_0.1.0_amd64.AppImage
/home/runner/work/www.desmos.com/www.desmos.com/src-tauri/target/release/bundle/appimage/app_0.1.0_amd64.AppImage.tar.gz
/home/runner/work/www.desmos.com/www.desmos.com/src-tauri/target/release/bundle/appimage/app_0.1.0_amd64.AppImage.tar.gz.sig
Error: No artifacts were found.
```

I have to create a package.json which has a name field, the value needs to be the same as `productName` in `custom-config.json`.

See https://github.com/liudonghua123/www.desmos.com/actions/runs/6158876952/job/16712538617#step:8:550, https://github.com/liudonghua123/www.desmos.com/actions/runs/6166685756/workflow#L43-L54,

**Comment by jessekrubin** [comment]
I/we am/are experiencing this as well (cc @grahamkrubin)

**Comment by FabianLars** [comment]
@jessekrubin Are you also setting the app name in a custom tauri config file you inject via `args: -c config.json` ?

tbh that's definitly something i did not expect when i added support for the `--config` flag in the action and removed the old init config (stupid oversight on my end) and the flow is a bit awkward now.

I'm a bit unsure which way forward is the most sensible here 🤔 We could read the config parameter for initializing the app too but since that's not the idea behind the flag it may feel counter intuitive for users, so i wonder if maybe an explicit setting like distPath makes more sense instead. What do you all think?

**Comment by liudonghua123** [comment]
How about add `name` (or `appName`) and `version` (or `appVersion`) options, which overwrite corresponding configuration of `package.json` if existed, and the highest priority config.json overwrite both of them finally?
