### ISSUE TITLE
Artifacts to include platform name

### ISSUE THREAD

**Issue by ogtfaber** [tauri-apps/tauri-action#571]
Is there a reason why the asset name does not include the name of the platform? It would be very helpful to do this, e.g. to make the output of the action compatible with platforms like AnyStack (https://anystack.sh/docs/integrations/tauri#start).

`app-name.{platform}-{arch}.tar.gz`

Happy to create a PR or check if there's another way to do this.

**Comment by FabianLars** [comment]
> Is there a reason why the asset name does not include the name of the platform?

Mainly because the action doesn't modify the names and just re-uses the names the tauri cli gives the bundles. And we never thought about the platform names in particular because the file types are already unique per platform.

That said, this is part of https://github.com/tauri-apps/tauri-action/issues/215 so it's planned at least.
