### ISSUE TITLE
What should I do to handle this RGBA issue?

### ISSUE THREAD

**Issue by adoin** [tauri-apps/tauri-action#670]
```
error: proc macro panicked
 --> src/main.rs:6:10
  |
6 |     .run(tauri::generate_context!())
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: icon /home/runner/work/paint-board/paint-board/src-tauri/icons/icon.png is not RGBA

error: could not compile `app` (bin "app") due to previous error
       Error failed to build app: failed to build app
Error: Command failed with exit code 1: pnpm tauri build
```

**Comment by FabianLars** [comment]
Well, rgba is a hard requirement for the icon so either try to export it differently from whatever program you used to create it, or try the `tauri icon` command which _should_ forcefully add transparency.

p.s. this issue is actually unrelated to this repo, tauri-action simply invokes tauri's cli & build command so this comes from tauri directly.
