### ISSUE TITLE
actions does not read config file by `--config` flag

### ISSUE THREAD

**Issue by honnip** [tauri-apps/tauri-action#712]
I'm working on https://github.com/honnip/gitbutler

configuration:
```yaml
with:
  args: "--config ${{ env.channel == 'nightly' && 'tauri.conf.nightly.json' || 'tauri.conf.release.json' }} --features ${{ env.channel == 'nightly' && 'devtools' || '' }}"
```
actions log:
```log
Run tauri-apps/tauri-action@v0
  with:
    args: --config tauri.conf.release.json --features 
    releaseName: GitButler release __VERSION__
    tagName: release/__VERSION__
    appVersion: 0.10.14
    releaseDraft: true
    prerelease: false
    projectPath: .
    includeDebug: false
    includeRelease: true
    includeUpdaterJson: true
    updaterJsonKeepUniversal: false
  env:
    SENTRY_AUTH_TOKEN: 
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
    CACHE_ON_FAILURE: false
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    STORE_PATH: /home/runner/setup-pnpm/node_modules/.bin/store/v3
    channel: release
    bump: patch
    version: 0.10.14
    GITHUB_TOKEN: ***
    TAURI_PRIVATE_KEY: ***
    TAURI_KEY_PASSWORD: ***
Unexpected token 'a', "tauri.conf."... is not valid JSON
```

I tried `./gitbutler-app/tauri.conf.release.json`, `./tauri.conf.release.json` and `../gitbutler-app/tauri.conf.release.json` with no luck.

I don't know if this is the cause, but when I specify the version with `appVersion`, `___version__` shows `0.0.0`

**Comment by FabianLars** [comment]
Hi, thanks for reaching out. What exactly was the issue when you tried `./gitbutler-app/tauri.conf.release.json` ?
I think those 2 runs are relevant for that <https://github.com/honnip/gitbutler/actions/runs/7989889685/job/21817416492> (without ./) and <https://github.com/honnip/gitbutler/actions/runs/7990149537/job/21818311403> (with ./).

at first glance they look correct to me? The `Unexpected token` error isn't a fail on its own, the action just tries to read the config flag as a json string first and falls back to reading it as a file path on error. I guess i could/should hide the error though or prepend a message saying what it means. Assuming of course the error is not related to the issue here.

p.s. the config flag is indeed relative to the current working dir or `projectPath` if defined so the `gitbutler-app` part should be required.

**Comment by FabianLars** [comment]
Okay, ignore me, it should have a different product name if it had worked, apologies.

**Comment by FabianLars** [comment]
Can you test the `fix-config-merge` branch by replacing `tauri-apps/tauri-action@v0` with `tauri-apps/tauri-action@fix-config-merge` please?

**Comment by FabianLars** [comment]
Okay i see it failed again, i now also see what my mistake was. I'll get back to you in a bit.

**Comment by honnip** [comment]
Sorry for late reply I actually nodded off for a second

I have to sleep before the work🫠 I'll come back to this in a few hours..

**Comment by FabianLars** [comment]
It looks like there was a successful run somehow even tho the implementation still didn't look right to me but i've rewritten the whole config handling now so i'd appreciate it if you could test it once more whenever you have time :)
